//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20MCA135_Assignment5.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public string sdegree { get; set; }
        public string scity { get; set; }
        public string gender { get; set; }
    }
}
